name: Build
on:
  workflow_dispatch: # for testing
  push:
    branches:
      - 'develop'

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_integrity:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            tox-env-py: "39"
          - python-version: "3.10"
            tox-env-py: "310"
          - python-version: "3.11"
            tox-env-py: "311"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Installing python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Code instrumentation
        run: |
          tox -e tests-py${{ matrix.tox-env-py }}-lin
  call-notify-to-teams:
    needs: [check_integrity]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: ./.github/workflows/notify_teams.yml
    secrets: inherit
