name: Nightly Regression Test
on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    - cron: "0 15 * * 2-6" # Every day at 12:00 AM in Korea time
defaults:
  run:
    shell: bash
jobs:
  nightly_regression_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-2022']
        python-version: ['3.9', '3.10', '3.11']
        include:
          - os: "ubuntu-20.04"
            tox-env-os: "lin"
          - os: "windows-2022"
            tox-env-os: "win"
          - python-version: "3.9"
            tox-env-py: "39"
          - python-version: "3.10"
            tox-env-py: "310"
          - python-version: "3.11"
            tox-env-py: "311"
    name: nightly regression test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Installing python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Nightly regression testing
        run: |
          # python -m pytest -v --html=nightly_regression_test_report.html
          tox -e tests-py${{ matrix.tox-env-py }}-${{ matrix.tox-env-os }}
      - name: Upload test results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: nightly-results-py${{ matrix.tox-env-py }}-${{ matrix.tox-env-os }}
          path: .tox/results-tests-py${{ matrix.tox-env-py }}-${{ matrix.tox-env-os }}.csv
  call-notify-to-teams:
    needs: [nightly_regression_test]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: ./.github/workflows/notify_teams.yml
    secrets: inherit
