name: PR Test
on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
permissions:
  contents: read

jobs:
  pr_test:
    if: |
      github.event.pull_request.draft == false &&
      !(startsWith(github.event.pull_request.title, '[WIP]')) &&
      !(startsWith(github.event.pull_request.title, '[Dependent]'))
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-2022']
        python-version: ['3.10']
        include:
          - python-version: "3.10"
            tox-env-py: "310"
          - os: "ubuntu-20.04"
            tox-env-os: "lin"
          - os: "windows-2022"
            tox-env-os: "win"
    name: pr test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Installing python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Unit testing
        run: |
          tox -vvv -e tests-py${{ matrix.tox-env-py }}-${{ matrix.tox-env-os }} --develop -- tests/unit --cov --cov-report=xml
      - name: Integration testing
        run: |
          tox -vvv -e tests-py${{ matrix.tox-env-py }}-${{ matrix.tox-env-os }} -- tests/integration
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
        with:
          flags: ${{ matrix.os }}_Python-${{ matrix.python-version }}
