name: Weekly Stability Test
on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    # every 7PM on Sunday
    - cron: "0 19 * * 0"

# This is what will cancel the workflow concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  weekly_stability_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-2022']
        python-version: ['3.10']
        include:
          - python-version: "3.10"
            tox-env-py: "310"
          - os: "ubuntu-20.04"
            tox-env-os: "lin"
          - os: "windows-2022"
            tox-env-os: "win"
    name: stability test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Installing python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Stability testing
        run: |
          tox -e stability-${{ matrix.tox-env-os }}
      - name: Upload test results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: results-stability-${{ matrix.tox-env-os }}
          path: .tox/results-stability-${{ matrix.tox-env-os }}.csv
  call-notify-to-teams:
    needs: [weekly_stability_test]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: ./.github/workflows/notify_teams.yml
    secrets: inherit
